

Backward Elimination


In [3]:
# 1.importing libraries

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd


In [4]:
# 2.importing datasets

data_set = pd.read_csv('/content/50_CompList.csv')
print(data_set.to_string())


    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

In [5]:
# 3.Extracting Independent and dependent Variable

x = data_set.iloc[:, :-1].values
y = data_set.iloc[:, 4].values

In [6]:
# 4.display x and y

df1=pd.DataFrame(x)
print("X Data")
print(df1.to_string())
df2=pd.DataFrame(y)
print("Y Data")
print(df2.to_string())


X Data
            0          1          2           3
0    165349.2   136897.8   471784.1    New York
1    162597.7  151377.59  443898.53  California
2   153441.51  101145.55  407934.54     Florida
3   144372.41  118671.85  383199.62    New York
4   142107.34   91391.77  366168.42     Florida
5    131876.9   99814.71  362861.36    New York
6   134615.46  147198.87  127716.82  California
7   130298.13  145530.06  323876.68     Florida
8   120542.52  148718.95  311613.29    New York
9   123334.88  108679.17  304981.62  California
10  101913.08  110594.11  229160.95     Florida
11  100671.96   91790.61  249744.55  California
12   93863.75  127320.38  249839.44     Florida
13   91992.39  135495.07  252664.93  California
14  119943.24  156547.42  256512.92     Florida
15  114523.61  122616.84  261776.23    New York
16   78013.11  121597.55  264346.06  California
17   94657.16  145077.58  282574.31    New York
18   91749.16  114175.79  294919.57     Florida
19    86419.7  153514.11        0

In [7]:
# 5.Catgorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x= LabelEncoder()

In [8]:
# 6.transforming to 0,1 and 2
x[:, 3] = labelencoder_x.fit_transform(x[:, 3])
df2=pd.DataFrame(x)
print(df2)


            0          1          2  3
0    165349.2   136897.8   471784.1  2
1    162597.7  151377.59  443898.53  0
2   153441.51  101145.55  407934.54  1
3   144372.41  118671.85  383199.62  2
4   142107.34   91391.77  366168.42  1
5    131876.9   99814.71  362861.36  2
6   134615.46  147198.87  127716.82  0
7   130298.13  145530.06  323876.68  1
8   120542.52  148718.95  311613.29  2
9   123334.88  108679.17  304981.62  0
10  101913.08  110594.11  229160.95  1
11  100671.96   91790.61  249744.55  0
12   93863.75  127320.38  249839.44  1
13   91992.39  135495.07  252664.93  0
14  119943.24  156547.42  256512.92  1
15  114523.61  122616.84  261776.23  2
16   78013.11  121597.55  264346.06  0
17   94657.16  145077.58  282574.31  2
18   91749.16  114175.79  294919.57  1
19    86419.7  153514.11        0.0  2
20   76253.86   113867.3  298664.47  0
21   78389.47  153773.43  299737.29  2
22   73994.56  122782.75  303319.26  1
23   67532.53  105751.03  304768.73  1
24   77044.01   99281.34 

In [9]:
# 7.State column ,Transforming
ct = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)
#Transformed State column
df4=pd.DataFrame(x)
print(df4)

      0    1    2          3          4          5
0   0.0  0.0  1.0   165349.2   136897.8   471784.1
1   1.0  0.0  0.0   162597.7  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0   131876.9   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  1

In [10]:
# 8.Avoiding the dummy variable trap:
x = x[:, 1:]
print("X")
print(x)

X
[[0.0 1.0 165349.2 136897.8 471784.1]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 0.0 134615.46 147198.87 127716.82]
 [1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 120542.52 148718.95 311613.29]
 [0.0 0.0 123334.88 108679.17 304981.62]
 [1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 93863.75 127320.38 249839.44]
 [0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 86419.7 153514.11 0.0]
 [0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 73994.56 122782.75 303319.26]
 [1.0 0.0 67532.53 105751.03 304768.73]
 [0.0 1.0 77044.01 99281.34 140574.81]
 

In [12]:
# 9.With out dummy
df5=pd.DataFrame(x)
print(df5)

      0          1          2          3
0   1.0   165349.2   136897.8   471784.1
1   0.0   162597.7  151377.59  443898.53
2   0.0  153441.51  101145.55  407934.54
3   1.0  144372.41  118671.85  383199.62
4   0.0  142107.34   91391.77  366168.42
5   1.0   131876.9   99814.71  362861.36
6   0.0  134615.46  147198.87  127716.82
7   0.0  130298.13  145530.06  323876.68
8   1.0  120542.52  148718.95  311613.29
9   0.0  123334.88  108679.17  304981.62
10  0.0  101913.08  110594.11  229160.95
11  0.0  100671.96   91790.61  249744.55
12  0.0   93863.75  127320.38  249839.44
13  0.0   91992.39  135495.07  252664.93
14  0.0  119943.24  156547.42  256512.92
15  1.0  114523.61  122616.84  261776.23
16  0.0   78013.11  121597.55  264346.06
17  1.0   94657.16  145077.58  282574.31
18  0.0   91749.16  114175.79  294919.57
19  1.0    86419.7  153514.11        0.0
20  0.0   76253.86   113867.3  298664.47
21  1.0   78389.47  153773.43  299737.29
22  0.0   73994.56  122782.75  303319.26
23  0.0   67532.

In [13]:
# 10.Splitting the dataset into training and test set.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [14]:
# 11.Fitting the MLR model to the training set:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train, y_train)


LinearRegression()

In [15]:
# 12.Predicting the Test set result;
y_pred = regressor.predict(x_test)


In [19]:
# 13.Checking the score
print('Train Score: ', regressor.score(x_train, y_train)*100,"%")
print('Test Score: ', regressor.score(x_test, y_test)*100,"%")
pre=[[1.0,0.0,165385.5,136222.6]]


Train Score:  95.01020786438474 %
Test Score:  93.67033175940503 %


In [20]:
# 14.Predicting the  result of 'pre'
pred = regressor.predict(pre)

print(pred)

[53595.36616693]
